# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Academic Portfolio',              url: 'academic-portfolio'}
- {name: 'Professional Work',              url: 'professional-work'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:  'https://www.linkedin.com/in/redefiningvicky/'}
- {icon: 'instagram', link:  'https://instagram.com/redefiningvicky/'}
